### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by AbrarHabib** [jdtuck/fdasrvf_MATLAB#5]
Hello,

I find the number of functions in fdasrvf Matlab File Exchange overwhelming and it's not clear where I should start or the categories of all the functions. Is there a tutorial or some instructions that can help categorize the functions and guide me through which function (or function category) I should start with?

**Comment by jdtuck** [comment]
What are you trying to do?

**Comment by AbrarHabib** [comment]
First of all, thank you for your prompt response.
To answer your question, I want to use functional data analysis to fit functions to observed and simulated hydrological data. After that, I want to change the simulated data until the fitted function is statistically similar to the function fitted to the observed data (basically I'm calibrating the hydrological model but instead of using error functions such as least squares error I want to use functional data analysis to benefit from it's holistic representation of the data). While I do that I might also investigate how changes to the parameters of the hydrological model relate to the parameters of the fitted function.

**Comment by jdtuck** [comment]
Ok use just use standard interpolation to make sure you have vectors represented of functional data. No need for the package here. On your next point are you having issues with phase variability?

Also have you read the papers associated with the code listed on the README?

**Comment by AbrarHabib** [comment]
Could you please elaborate on your point about standard interpolation?

Yes, there is phase variability.

I am in the process of reading them. I had a look at the thesis and I started reading the most recent journal paper and I intend to work my way back.

**Comment by AbrarHabib** [comment]
I meant to say basis functions actually. According to what I understand, with functional data analysis, we can fit basis functions to data. The basis functions can be fourrier, polynomial, splines, etc. the benefit of this is that i can represent the entire 'shape' of the dataset for calibration rather than just parts of the dataset such as only the peak values or the low values.

**Comment by AbrarHabib** [comment]
It is useful for hydrologists in this sense and there are papers explaining its implementation in various ways.

**Comment by jdtuck** [comment]
One theory is to use basis functions (see Ramsay and Silverman). We work from the continuous domain directly and do not project onto a basis. You will want to start with the fdawarp class to align your data and then use elastic distance for your task. We also have a full Bayesian  model calibration code we will release soon.

**Comment by AbrarHabib** [comment]
ok, I'll try that. Thanks!
